openapi: '3.0.1'
info:
  version: '1.0.0'
  title: Checkout.com API Reference
  x-logo:
    url: 'https://assets.checkout.com/docs/logos/logo-checkout-api-dark.svg'
    backgroundColor: '#E6E7EC'
    altText: 'Checkout.com API logo'
  contact:
    name: Checkout.com Support
    url: 'https://checkout.com'
    email: support@checkout.com
  license:
    name: Checkout.com
    url: 'https://checkout.com/api/license/'
  termsOfService: 'https://checkout.com/terms/'
  description: >
    ##  Get started

    Checkout.com provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard <a href="https://www.checkout.com/docs/four/resources/codes/http-response-codes">HTTP response codes</a>.

    You can consume the APIs directly using your favorite HTTP/REST library.

    We have a testing environment called sandbox, which you can <a href="https://www.checkout.com/get-test-account">sign up for</a> to test API calls without affecting live data.

    # Authentication

    When you sign up for an account, you are given a public key, and either a set of client credentials or a secret key. You authenticate with our API by following the appropriate authentication flow, using either your API keys or your client credentials.

    Unless explicitly stated, all endpoints require authentication using either your client credentials or your secret key. Public keys should only be used in JavaScript or native applications.

    - <b>Client-side authentication</b>. Use your [public key](#section/Authentication/ApiPublicKey) for client-side authentication. It only has access to a limited set of our APIs – mostly those called as part of your payment environment.

    - <b>Server-to-server authentication</b>. Use your [secret key](#section/Authentication/ApiSecretKey) or [client credentials](#section/Authentication/OAuth) for server-to-server communication. Support for API keys depends on the endpoint.

    Never share your client credentials, API keys, or access tokens. Keep them guarded and secure.

    # Changelog

      | Date       | Description of change                                                         |
      | ---------- | ----------------------------------------------------------------------------- |
      | 2022/03/02 | Adds Transfers and Balances                                                   |
      | 2022/02/23 | Adds Hosted Payments Page and Payment Links                                   |
      | 2022/02/18 | Added `Increment Payment Authorization` code samples for Java & C#            |
      | 2022/02/02 | Adds `active` property for workflows                                          |
      | 2022/01/26 | Update code samples for Java.                                                 |
      | 2022/01/25 | Update code samples for C#.                                                   |
      | 2022/01/19 | Added test a workflow endpoint.                                               |
      | 2022/01/13 | Update code samples for Node JS.                                              |
      | 2021/11/29 | Increase max length of the NAS `success_url` and `failure_url` fields of the payment request (both from 255 to 1024).|
      | 2021/11/11 | Added `3ds.challenge_indicator` to card payment requests.                     |
      | 2021/11/03 | Adds `identification` object under parent `sender` object in payment request. |
      | 2021/10/18 | Added the `marketplaces.sub-entities` object to support split payments.       |
servers:
  - url: https://api.checkout.com
    description: Live API
  - url: https://api.sandbox.checkout.com
    description: Sandbox API
tags:
  - name: Access
    description: Create an access token to begin using our APIs.
  - name: Payments
    description: Process and manage payments from a variety of sources and to various destinations all within one integration.
  - name: Payment Links
    description: Create a Payment Link to accept and process payment details.
  - name: Hosted Payments Page
    description: Create a Hosted Payments Page to accept and process payment details.
  # - name: Sources
  #   description: Create a payment source for a customer that you can use for one or more payments.
  - name: Tokens
    description: Create a token that represents a card's details that you can later use to request a payment, without you having to process or store any sensitive information.
  - name: Instruments
    description: Create and manage your card and bank account payment instruments.
  - name: Forex
    description: Checkout.com Foreign Exchange services
  - name: Disputes
    description: Keep track of and act on your open disputes (also known as chargebacks) to submit the best possible response.
  - name: Marketplace
    description: Manage all your sub-entities (also known as sub-merchants) through one integration, globally.
  - name: Sessions
    description: Use Sessions to authenticate transactions with 3D Secure (3DS) and comply with Strong Customer Authentication (SCA) requirements.
  - name: Workflows
    description: Use Workflows to start receiving webhook notifications for your payments, disputes, and marketplace sub-entities.
  - name: Risk
    description: Evaluate the risk of a transaction at the pre-authentication and pre-capture stages of the payment process.
  - name: Apple Pay
    description: Manage your Apple Pay certificates in order to process payments via Apple Pay.
  - name: Transfers
    description: Transfer funds while managing the entities to transfer money to recoup funds from a seller, return money from a refund or to make up the difference when running a promotion.
  - name: Balances
    description: View balances for currency accounts belonging to an entity.

  # - name: Files
  #   description: |
  #     Upload files to be used as input to other APIs

x-tagGroups:
  - name: Set up
    tags:
      - Access
  - name: Handle payments and payouts
    tags:
      - Payments
      - Payment Links
      - Hosted Payments Page
      - Forex
      - Apple Pay
      - Transfers
      - Balances
  - name: Stored payment details
    tags:
      - Tokens
      - Instruments
      - Customers
  - name: Risk management
    tags:
      - Sessions
      - Disputes
      - Risk
  - name: Notifications
    tags:
      - Workflows
  - name: Marketplace
    tags:
      - Marketplace
paths:
  /:
    post:
      tags:
        - Marketplace
      security:
        - OAuth:
            - files
      servers:
        - url: https://files.checkout.com
          description: Production server
        - url: https://files.sandbox.checkout.com
          description: Sandbox server
      summary: Upload a file
      description: >-
        Our <a href="https://checkout.com/docs/four/marketplaces" target="_blank">Marketplace</a> solution provides an easy way to upload identity documentation required for full due diligence. Please <strong>note</strong> that the sub-domain – https://files.checkout.com – is slightly different to Checkout.com's other endpoints. <br><br>Read the <a href="https://checkout.com/docs/four/marketplaces/onboarding/api/full/upload-a-file" target="_blank">documentation</a> for more information.
  /applepay/certificates:
    post:
      tags:
        - Apple Pay
      security:
        - ApiPublicKey: [ ]
      summary: Upload a payment processing certificate
      description: |
        Upload a payment processing certificate. This will allow you to start processing payments via Apple Pay.
  /applepay/signing-requests:
    post:
      tags:
        - Apple Pay
      security:
        - ApiPublicKey: [ ]
      summary: Generate a certificate signing request
      description: |
        Generate a certificate signing request. You'll need to upload this to your Apple Developer account to download a payment processing certificate.
  /balances/{id}:
    get:
      summary: Retrieve entity balances
      description: Use this endpoint to retrieve balances for each currency account belonging to an entity.
      security:
        - OAuth:
            - marketplace
      tags:
        - Balances
  /connect/token:
    servers:
      - url: https://access.checkout.com
        description: Live API
      - url: https://access.sandbox.checkout.com
        description: Sandbox API
    post:
      summary: Request an access token
      tags:
        - Access
      description: OAuth endpoint to exchange your access key ID and access key secret for an access token.
  /customers:
    post:
      tags:
        - Customers
      security:
        - OAuth:
            - vault
            - vault:customers
        - ApiSecretKey: []
      summary: Create a customer
      description: >
        <a href="https://www.checkout.com/docs/four/payments/store-payment-details/customers" target="_blank">Store a customer's details in a customer object to reuse in future payments</a>. When creating a customer, you can link payment instruments – the customer `id` returned can be passed as a source when making a payment.
        <br/><br>
        **NOTE:** Specify a `default` instrument, otherwise the `instruments` array will not be saved on creation.
  /customers/{identifier}:
    get:
      security:
        - OAuth:
            - vault
            - vault:customers
        - ApiSecretKey: [ ]
      tags:
        - Customers
      summary: Get customer details
      description: Returns the details of a customer and their payment instruments.
    patch:
      tags:
        - Customers
      security:
        - OAuth:
            - vault
            - vault:customers
        - ApiSecretKey: [ ]
      summary: Update customer details
      description: Update the details of a customer and link payment instruments to them.
    delete:
      tags:
        - Customers
      security:
        - OAuth:
            - vault
            - vault:customers
        - ApiSecretKey: [ ]
      summary: Delete a customer
      description: Delete a customer and all of their linked payment instruments.
  /disputes:
    get:
      tags:
        - Disputes
      security:
        - OAuth:
            - disputes
            - disputes:view
        - ApiSecretKey: [ ]
      summary: Get disputes
      description: >-
        Returns a list of all disputes against your business. The results will be
        returned in reverse chronological order, showing the last modified dispute
        (for example, where you've recently added a piece of evidence) first. You
        can use the optional parameters below to skip or limit results.
  /disputes/{dispute_id}:
    get:
      tags:
        - Disputes
      security:
        - OAuth:
            - disputes
            - disputes:view
        - ApiSecretKey: [ ]
      summary: Get dispute details
      description: Returns all the details of a dispute using the dispute identifier.
  /disputes/{dispute_id}/accept:
    post:
      tags:
        - Disputes
      security:
        - OAuth:
            - disputes
            - disputes:accept
        - ApiSecretKey: [ ]
      summary: Accept dispute
      description: >-
        If a dispute is legitimate, you can choose to accept it. This will close it
        for you and remove it from your list of open disputes. There are no further
        financial implications.
  /disputes/{dispute_id}/evidence:
    put:
      tags:
        - Disputes
      security:
        - OAuth:
            - disputes
            - disputes:provide-evidence
        - ApiSecretKey: [ ]
      summary: Provide dispute evidence
      description: >
        Adds supporting evidence to a dispute. Before using this endpoint, you first
        need to [upload your files](#tag/Disputes/paths/~1files/post) using the file
        uploader. You will receive a file id (prefixed by `file_`) which you can
        then use in your request.
        Note that this only attaches the evidence to the dispute, it does not send
        it to us. Once ready, you will need to submit it.
        **You must provide at least one evidence type in the body of your request.**
    get:
      tags:
        - Disputes
      security:
        - OAuth:
            - disputes
            - disputes:view
        # - ApiKey: []
      summary: Get dispute evidence
      description: >
        Retrieves a list of the evidence submitted in response to a specific
        dispute.
    post:
      tags:
        - Disputes
      security:
        - OAuth:
            - disputes
            - disputes:provide-evidence
        # - ApiKey: []
      summary: Submit dispute evidence
      description: >-
        With this final request, you can submit the evidence that you have
        previously provided. Make sure you have provided all the relevant
        information before using this request. You will not be able to amend your
        evidence once you have submitted it.
  /files:
    post:
      tags:
        - Disputes
      security:
        - OAuth:
            - disputes
            - disputes:provide-evidence
        - ApiSecretKey: [ ]
      summary: Upload file
      description: >-
        Upload a file to use as evidence in a dispute. Your file must be in either
        JPEG/JPG, PNG or PDF format, and be no larger than 4MB.
  /files/{file_id}:
    get:
      tags:
        - Disputes
      security:
        - OAuth:
            - disputes
            - disputes:view
        - ApiSecretKey: [ ]
      summary: Get file information
      description: Retrieve information about a file that was previously uploaded.
  /workflows:
    get:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:workflows
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Get all workflows
      description: |
        Get all workflows
    post:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:workflows
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Add a workflow
      description: |
        Add a new Flow workflow
  /workflows/{workflowId}:
    get:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:workflows
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Get a workflow
      description: |
        Get the details of a workflow
    delete:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:workflows
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Remove a workflow
      description: |
        Removes a workflow so it is no longer being executed.
        Actions of already executed workflows will be still processed.
    patch:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:workflows
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Patch a workflow
      description: |
        Update the name of a workflow.
  /workflows/{workflowId}/actions/{workflowActionId}:
    put:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:workflows
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Update a workflow action
      description: |
        Update a workflow action.
  /workflows/{workflowId}/conditions/{workflowConditionId}:
    put:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:workflows
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Update a workflow condition
      description: |
        Update a workflow condition.
  /workflows/{workflowId}/test:
    post:
      servers:
        - url: https://api.sandbox.checkout.com
          description: Sandbox
      security:
        - OAuth:
            - flow
            - flow:workflows
      tags:
        - Workflows
      summary: Test a workflow
      description: >
        Validate a workflow in our Sandbox environment.
  /workflows/event-types:
    get:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:workflows
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Get event types
      description: |
        Get a list of sources and their events for building new workflows
  /workflows/events/{eventId}:
    get:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:events
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Get an event
      description: |
        Get the details of an event
  /workflows/events/{eventId}/reflow:
    post:
      security:
        - OAuth:
            - flow
            - flow:reflow
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Reflow by event
      description: |
        Reflows a past event denoted by the event ID and triggers the actions of any workflows with matching conditions.
  /workflows/events/{eventId}/workflow/{workflowId}/reflow:
    post:
      security:
        - OAuth:
            - flow
            - flow:reflow
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Reflow by event and workflow
      description: |
        Reflows a past event by event ID and workflow ID. Triggers all the actions of a specific event and workflow combination if the event denoted by the event ID matches the workflow conditions.
  /workflows/events/reflow:
    post:
      security:
        - OAuth:
            - flow
            - flow:reflow
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Reflow
      description: |
        Reflow past events attached to multiple event IDs and workflow IDs, or to multiple subject IDs and workflow IDs. If you don't specify any workflow IDs, all matching workflows will be retriggered.
  /workflows/events/subject/{subjectId}:
    get:
      servers:
        - url: https://api.checkout.com
          description: Live API
        - url: https://api.sandbox.checkout.com
          description: Sandbox API
      security:
        - OAuth:
            - flow
            - flow:events
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Get subject events
      description: |
        Get all events that relate to a specific subject
  /workflows/events/subject/{subjectId}/reflow:
    post:
      security:
        - OAuth:
            - flow
            - flow:reflow
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Reflow by subject
      description: |
        Reflows the events associated with a subject ID (for example, a payment ID or a dispute ID) and triggers the actions of any workflows with matching conditions.
  /workflows/events/subject/{subjectId}/workflow/{workflowId}/reflow:
    post:
      security:
        - OAuth:
            - flow
            - flow:reflow
        - ApiSecretKey: [ ]
      tags:
        - Workflows
      summary: Reflow by subject and workflow
      description: |
        Reflows the events associated with a subject ID (for example, a payment ID or a dispute ID) and triggers the actions of the specified workflow if the conditions match.
  /forex/quotes:
    post:
      tags:
        - Forex
      security:
        - OAuth:
            - fx
      summary: Request a quote
      description: |
        Request an exchange rate between a source and destination currency pair that will be used to process one or more payouts. You must submit a payout with the FX quote identifier before the quote expires. If the FX quote identifier is omitted from a payout, and the source and destination currencies differ, the current market exchange rate will be used.
  /hosted-payments:
    post:
      security:
        - ApiSecretKey: [ ]
      tags:
        - Hosted Payments Page
      summary: Create a Hosted Payments Page session
      operationId: createAHostedPaymentsSession
      description: |
        Create a Hosted Payments Page session and pass through all the payment information, like the amount, currency, country and reference.
    
        To get started with our Hosted Payments Page, contact your Solutions Engineer or integration@checkout.com.
  /hosted-payments/{id}:
    get:
      security:
        - ApiSecretKey: []
      tags:
        - Hosted Payments Page
      summary: Get Hosted Payments Page details
      operationId: getHostedPaymentsPageDetails
      description: |
        Retrieve details about a specific Hosted Payments Page using the ID returned when it was created. In the response, you will see the status of the Hosted Payments Page.<br><br>
        For more information, see the <a target="_blank" href="https://docs.checkout.com/integrate/hosted-payments-page">Hosted Payments Page documentation</a>.
  /instruments:
    post:
      tags:
        - Instruments
      security:
        - OAuth:
            - vault
            - vault:instruments
        - ApiSecretKey: [ ]
      summary: Create an instrument
      description: |
        Create a card or bank account payment instrument to use for future payments and payouts. <br><br>The parameters you need to provide when creating a bank account payment instrument depend on the account's country and currency. See <a href="https://docs.checkout.com/four/bank-payouts/payout-formatting" target="_blank">our docs</a> and the <a href="#tag/Instruments/paths/~1validation~1bank-accounts~1{country}~1{currency}/get">GET endpoint below</a>.
  /instruments/{id}:
    get:
      security:
        - OAuth:
            - vault
            - vault:instruments
        - ApiSecretKey: [ ]
      tags:
        - Instruments
      summary: Get instrument details
      operationId: getInstrumentDetails
      description: Retrieve the details of a payment instrument.
    patch:
      tags:
        - Instruments
      security:
        - OAuth:
            - vault
            - vault:instruments
        - ApiSecretKey: [ ]
      summary: Update an instrument
      description: |
        Update the details of a payment instrument.
    delete:
      tags:
        - Instruments
      security:
        - OAuth:
            - vault
            - vault:instruments
        - ApiSecretKey: [ ]
      summary: Delete an instrument
      description: |
        Delete a payment instrument.
  /marketplace/entities:
    post:
      description: |
        Onboard a sub-entity so they can start receiving payments. Once created, Checkout.com will run due diligence checks.
        If the checks are successful, we'll enable payment capabilities for that sub-entity and they will start receiving payments.
      summary: Onboard a sub-entity
      security:
        - OAuth:
            - marketplace
      tags:
        - Marketplace
  /marketplace/entities/{id}:
    get:
      description: Use this endpoint to retrieve a sub-entity and its full details.
      summary: Get sub-entity details
      security:
        - OAuth:
            - marketplace
      tags:
        - Marketplace
    put:
      description: |
        You can update all fields under the Contact details, Profile, and Company objects. You can also add <strong>identification</strong> information to complete due diligence requirements.<br><br>
        <strong>Note:</strong> when you update a sub-entity we may conduct further due diligence checks when necessary. During these checks, your payment capabilities will remain the same.
      summary: Update sub-entity details
      security:
        - OAuth:
            - marketplace
      tags:
        - Marketplace
  /marketplace/entities/{id}/instruments:
    post:
      description: Create a bank account payment instrument for your sub-entity that you can later use as the destination for their payouts.
      summary: Add a payment instrument
      security:
        - OAuth:
            - marketplace
      tags:
        - Marketplace
  /payment-links:
    post:
      security:
        - ApiSecretKey: [ ]
      tags:
        - Payment Links
      summary: Create a Payment Link
      operationId: createAPaymentLinkSession
      description: |
        Create a Payment Link and pass through all the payment information, like the amount, currency, country and reference.
  /payment-links/{id}:
    get:
      security:
        - ApiSecretKey: []
      tags:
        - Payment Links
      summary: Get Payment Link details
      operationId: getPaymentLinkDetails
      description: |
        Retrieve details about a specific Payment Link using its ID returned when the link was created. In the response, you will see the status of the Payment Link.<br><br>
        For more information, see the <a target="_blank" href="https://docs.checkout.com/integrate/payment-links">Payment Links documentation</a>.
  /payments:
    post:
      security:
        - OAuth:
            - gateway
            - gateway:payment
        - ApiSecretKey: [ ]
      tags:
        - Payments
      summary: Request a payment or payout
      operationId: requestAPaymentOrPayout
      description: |
        Send a payment or payout.<br><br><b>Note</b>: successful payout requests will always return a 202 response.
  /payments/{id}:
    get:
      tags:
        - Payments
      security:
        - OAuth:
            - gateway
            - gateway:payment-details
        - ApiSecretKey: [ ]
      summary: Get payment details
      description: |
        Returns the details of the payment with the specified identifier string.
    
        If the payment method requires a redirection to a third party (e.g., 3D Secure),
        the redirect URL back to your site will include a `cko-session-id` query parameter
        containing a payment session ID that can be used to obtain the details of the payment, for example:
    
        http://example.com/success?cko-session-id=sid_ubfj2q76miwundwlk72vxt2i7q.
  /payments/{id}/actions:
    get:
      tags:
        - Payments
      security:
        - OAuth:
            - gateway
            - gateway:payment-details
        - ApiSecretKey: [ ]
      summary: Get payment actions
      description: |
        Returns all the actions associated with a payment ordered by processing date in descending order (latest first).
  /payments/{id}/authorizations:
    post:
      tags:
        - Payments
      security:
        - OAuth:
            - gateway
            - gateway:payment-authorizations
        - ApiSecretKey: [ ]
      summary: Increment authorization
      description: |
        Request an incremental authorization to increase the authorization amount or extend the authorization's validity period.
    
  /payments/{id}/captures:
    post:
      tags:
        - Payments
      security:
        - OAuth:
            - gateway
            - gateway:payment-captures
        - ApiSecretKey: [ ]
      summary: Capture a payment
      description: |
        Captures a payment if supported by the payment method.
    
        For card payments, capture requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the capture is successful.
  /payments/{id}/refunds:
    post:
      tags:
        - Payments
      security:
        - OAuth:
            - gateway
            - gateway:payment-refunds
        - ApiSecretKey: [ ]
      summary: Refund a payment
      description: |
        Refunds a payment if supported by the payment method.
    
        For card payments, refund requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the refund is successful.
  /payments/{id}/voids:
    post:
      tags:
        - Payments
      security:
        - OAuth:
            - gateway
            - gateway:payment-voids
        - ApiSecretKey: [ ]
      summary: Void a payment
      description: |
        Voids a payment if supported by the payment method.
    
        For card payments, void requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the void is successful.
  /risk/assessments/pre-authentication:
    post:
      security:
        - ApiSecretKey: [ ]
      tags:
        - Risk
      summary: Request a pre-authentication risk scan
      operationId: preAuthenticationRiskAssessment
      description: |
        Perform a pre-authentication fraud assessment using your defined risk settings.
        #parameters:
      # - $ref: '#/components/parameters/ckoIdempotencyKey'
  /risk/assessments/pre-capture:
    post:
      security:
        - ApiSecretKey: [ ]
      tags:
        - Risk
      summary: Request a pre-capture risk scan
      operationId: preCaptureRiskAssessment
      description: |
        Perform a pre-capture fraud assessment using your defined risk settings.<br><br> **Note**: If you’ve already requested a pre-authentication fraud assessment for the transaction, provide the `assessment_id` returned in that response in your request to carry over the data. If you do include the `assessment_id`, the other fields you provide in this request will only fill in any gaps in the data; they will not overwrite any data.
      # parameters:
      #   - $ref: '#/components/parameters/ckoIdempotencyKey'
  /sessions:
    post:
      tags:
        - Sessions
      security:
        - OAuth:
            - sessions:app
            - sessions:browser
      summary: Request a session
      description: |
        Create a payment session to authenticate a cardholder before requesting a payment.
        Payment sessions can be linked to one or more payments (in the case of recurring and other merchant-initiated payments).
    
        The `next_actions` object in the response tells you which actions can be performed next.
    
  /sessions/{id}:
    get:
      tags:
        - Sessions
      security:
        - OAuth:
            - sessions:app
            - sessions:browser
        - SessionSecret: [ ]
      summary: Get session details
      description: |
        Returns the details of the session with the specified identifier string.
  /sessions/{id}/collect-data:
    put:
      security:
        - OAuth:
            - sessions:app
            - sessions:browser
        - SessionSecret: [ ]
      summary: Update a session
      description: Update a session by providing information about the environment.
      tags:
        - Sessions
  /sessions/{id}/complete:
    post:
      security:
        - OAuth:
            - sessions:app
            - sessions:browser
        - SessionSecret: [ ]
      summary: Complete a session
      description: |
        Completes a session by posting the the following request to the callback URL (only relevant for non hosted sessions):
        ```
        {
           "session_id": "sid_llraltf4jlwu5dxdtprcv7ba5i",
           "amount" : 6540,
           "currency": "USD",
           "status": "approved",
           "authentication_type": "regular",
           "authentication_category": "payment",
           "reference": "ORD-5023-4E89",
           "approved": true,
           "protocol_version": "2.1.0",
           "response_code": "Y",
           "response_reason": "01",
           "cryptogram": "MTIzNDU2Nzg5MDA5ODc2NTQzMjE=",
           "eci": "05",
           "xid": "XSUErNftqkiTdlkpSk8p32GWOFA",
           "cardholder_info": "Card declined. Please contact your issuing bank.",
           "challenged": true
        }
        ```
        <br/>
        The fields of the above are the same as they would be in a GET session response
      tags:
        - Sessions
  /sessions/{id}/issuer-fingerprint:
    put:
      security:
        - OAuth:
            - sessions:browser
        - SessionSecret: [ ]
      summary: Update session 3DS Method completion indicator
      description: Update the session's 3DS Method completion indicator based on the result of accessing the 3DS Method URL.
      tags:
        - Sessions
  /tokens:
    post:
      tags:
        - Tokens
      security:
        - ApiPublicKey: [ ]
      summary: Request a token
      description: |
        Exchange card details for a reference token that can be used later to request a card payment. Tokens are single use and expire after 15 minutes.
        To create a token, please authenticate using your public key.
    
        **Please note:** You should only use the `card` type for testing purposes.
  /transfers:
    post:
      security:
        - OAuth:
            - marketplace:transfer:create
      description: |
        Initiate a transfer of funds from source entity to destination entity.
      summary: Initiate a transfer of funds
      tags:
        - Transfers
  /validation/bank-accounts/{country}/{currency}:
    get:
      tags:
        - Instruments
      security:
        - OAuth:
            - payouts:bank-details
      summary: Get bank account field formatting
      description: |
        Returns the bank account field formatting required to create bank account instruments or perform payouts for the specified country and currency.
components:
  securitySchemes:
    ApiPublicKey:
      description: |
        Public keys are used for client-side authentication, and should only be used in JavaScript or native applications.
      
        #### Format
      
        - Sandbox `pk_sbox_xxxxxxxxxxxxxxxxxxxxxxxxxx`
      
        - Production `pk_xxxxxxxxxxxxxxxxxxxxxxxxxx`
      
        When specifying your public key in the Authorization header, you must include the `Bearer` prefix. For example, `Bearer {{public API key}}`.
      name: Authorization
      type: apiKey
      in: header
      x-cko-type: publicKey
    ApiSecretKey:
      description: |
        You can use your secret API key in the Authorization header of your API requests for <a href="https://docs.checkout.com/four/resources/api-authentication/api-keys#APIkeys-Secretkeys" target="_blank">supported endpoints</a>.
      
        #### Format
      
        - Sandbox `sk_sbox_xxxxxxxxxxxxxxxxxxxxxxxxxx`
      
        - Production `sk_xxxxxxxxxxxxxxxxxxxxxxxxxx`
      
        ```
        curl --location --request POST 'https://api.checkout.com/payments' \
        --header 'Content-Type: application/json' \
        --header 'Accept: application/json' \
        --header 'Authorization: Bearer {{AccessToken}}' \
        --data-raw '{
        "amount": 10000,
        "currency": "USD",
        "reference": "Visa-USD-Test",
        ...
        }'
        ```
      
        When specifying your secret key in the Authorization header, you must include the `Bearer ` prefix. For example, `Bearer {{secret API key}}`.
      
      name: Authorization
      type: apiKey
      in: header
      x-cko-type: secretKey
    OAuth:
      type: oauth2
      description: |
        Your client credentials consist of an access key ID and an access key secret (corresponding to OAuth 2.0 client ID and client secret). You can exchange these for an access token by calling the [request an access token](#tag/Access/paths/~1connect~1token/post) endpoint. 
        You will need to authenticate using basic authentication, using your access key ID and access key secret as your username and password:
      
        ```
        curl --location --request POST 'https://access.checkout.com/connect/token' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --header 'Authorization: Basic dGVzdC1hY2Nlc3Mta2V5LWlkOnRlc3QtYWNjZXNzLWtleS1zZWNyZXQ=' \
        --data-urlencode 'grant_type=client_credentials' \
        --data-urlencode 'scope=gateway'
        ```
      
        The token server will return a Bearer `access_token` in JSON Web Token (JWT) format which you should use in the `Authorization`
        header of your API requests:
      
        ```
        curl --location --request POST 'https://api.checkout.com/payments' \
        --header 'Content-Type: application/json' \
        --header 'Accept: application/json' \
        --header 'Authorization: Bearer {{AccessToken}}' \
        --data-raw '{
          "amount": 10000,
          "currency": "USD",
          "reference": "Visa-USD-Test",
          ...
        }'
        ```
      
        Your access token will be valid for a length of time (in seconds) indicated by the `expires_in` field in the response. When it expires, you'll need to request a new one.
      
        Depending on the Environment against which you're making your requests against you'll need to request the token from a different Authorization Server.
      
        | Environment   |      Authorization Server                            |
        |---------------|------------------------------------------------------|
        | Sandbox       |  https://access.sandbox.checkout.com/connect/token   |
        | Production    |  https://access.checkout.com/connect/token           |
      
      flows:
        clientCredentials:
          tokenUrl: string
          scopes:
            vault: Access to all Vault resources
            'vault:instruments': Create instruments
            'vault:tokenization': Tokenize payment instruments
            gateway: Access to all Gateway resources
            'gateway:payment': Request payments
            'gateway:payment-details': Get payment details
            'gateway:payment-authorizations': Increment authorizations
            'gateway:payment-voids': Void payments
            'gateway:payment-captures': Capture payments
            'gateway:payment-refunds': Refund payments
            'fx': Foreign exchange services
            'payouts:bank-details': Get bank details
            sessions: Access to all Sessions resources
            'sessions:app': App-based authentication
            'sessions:browser': Browser-based authentication
            disputes: Access to all Disputes resources
            'disputes:view': View disputes
            'disputes:provide-evidence': Provide dispute evidence
            'disputes:accept': Accept disputes
            marketplace: Manage sub-entities
            flow: Access to all Flow resources
            'flow:workflows': Manage workflows
            'flow:events': Retrieve events
            files: Access to all Files resources
            'files:retrieve': Retrieve files
            'files:upload': Upload files
            'issuing:client': Access to all client-related resources
            'issuing:partner': Access to all partner-related resources
            risk: Access to all Risk resources
            'risk:assessment': Manage risk assessment
            'risk:settings': Manage risk settings
    SessionSecret:
      name: Authorization
      type: apiKey
      in: header
      description: >
        A base64 encoded value prefixed with `sek_` that gives access to client-side operations for a single authentication within the Sessions API. This value is returned as the `session_secret` when requesting a session.
